### ISSUE TITLE
Puppet server don't start automatically.

### ISSUE THREAD

**Issue by MaximSternberg** [graduway/psick#105]
## Expected Behavior 
After deploy puppet-server It must be running and ready to work. 

## Actual Behavior
Deploy using 'terragrunt apply' pass successfully. But puppet server does not running. If i starting puppet-server manually it works good.  

## Steps to Reproduce the Problem

0. install terragrunt on your pc (https://github.com/gruntwork-io/terragrunt)
1. Terminate current puppet-dev
2. Setup Graduway access key on your pc.
3. cd tfcode/environments/us-east-1/dev/gw-puppet/
4. Plan changes: terragrunt plan 
5. Apply changes: terragrunt apply
6. Check status of puppet-server.

**Comment by antgel** [comment]
@MaximSternberg I assigned it to @alvagante and put it in the Kanban project, please do this for future issues, thanks. :)

**Comment by MaximSternberg** [comment]
I attach to this server log file form puppet-server. On the end of this file have some warnings. Probably it will help.
`[mNotice: Compiled catalog for puppet.dev.us-east-1.graduway.com in environment production in 3.75 seconds [0m
 [0;32mInfo: Applying configuration version '503942e - Alessandro Franceschi, Fri Jan 4 11:48:02 2019 +0100 : Remove unused jenkins-qa.yaml'[0m
[1;31mError: Found 1 dependency cycle:
(Package[apt-transport-https] => Apt::Source[apt.postgresql.org] => Package[apt-transport-https])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz[0m
[1;31mError: Failed to apply catalog: One or more resource dependency cycles detected in graph[0m
Changes:
Events:
          Failure: 1
            Total: 1
Resources:
           Failed: 1
      Out of sync: 1
            Total: 1
Time:
         Last run: 1548253508
   Config retrieval: 4.24
            Total: 0.16
Version:
           Config: 503942e - Alessandro Franceschi, Fri Jan 4 11:48:02 2019 +0100 : Remove unused jenkins-qa.yaml
           Puppet: 6.1.0
-There were errors in the Puppet run-
Cloud-init v. 0.7.9 running 'modules:final' at Wed, 23 Jan 2019 14:19:49 +0000. Up 10.71 seconds.
2019-01-23 14:25:08,312 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-002 [1]
2019-01-23 14:25:08,414 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2019-01-23 14:25:08,415 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 0.7.9 finished at Wed, 23 Jan 2019 14:25:08 +0000. Datasource DataSourceEc2.  Up 329.53 seconds
`

[cloud-init-output.log](https://github.com/graduway/psick/files/2791082/cloud-init-output.log)

**Comment by olegy-ait** [comment]
It happened after upgrade puppetlabs/apt to 6.3.0. 
We need to pin puppetlabs/apt module to 6.2.1.

Here is a PR for it https://github.com/graduway/psick/pull/106

**Comment by olegy-ait** [comment]
Puppet agent tries to configure and start puppetdb before puppet master start.
Therefore it crashes with the error below.
@alvagante could you please check why it happens?

`Info: Class[Puppetdb::Server::Puppetdb]: Scheduling refresh of Service[puppetdb]
Notice: /Stage[main]/Puppetdb::Server/Cron[puppetdb-dlo-cleanup]/ensure: created
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: PEM files in /etc/puppetlabs/puppetdb/ssl are missing, we will move them into place for you
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: Warning: Unable to find all puppet certificates to copy
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: 
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   This tool requires the following certificates to exist:
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: 
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   * /etc/puppetlabs/puppet/ssl/certs/ca.pem
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   * /etc/puppetlabs/puppet/ssl/private_keys/puppet.dev.us-east-1.graduway.com.pem
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   * /etc/puppetlabs/puppet/ssl/certs/puppet.dev.us-east-1.graduway.com.pem
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: 
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   These files may be missing due to the fact that your host's Puppet
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   certificates may not have been signed yet, probably due to the
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   lack of a complete Puppet agent run. Try running puppet first, for
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   example:
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: 
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:       puppet agent --test
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: 
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   Afterwards re-run this tool then restart PuppetDB to complete the SSL
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:   setup:
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: 
Notice: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns:       puppetdb ssl-setup -f
Error: '/opt/puppetlabs/bin/puppetdb ssl-setup' returned 1 instead of one of [0]
Error: /Stage[main]/Psick::Puppet::Foss_master/Exec[puppetdb ssl-setup]/returns: change from 'notrun' to ['0'] failed: '/opt/puppetlabs/bin/puppetdb ssl-setup' returned 1 instead of one of [0]
Notice: /Stage[main]/Puppetdb::Server/Service[puppetdb]: Dependency Exec[puppetdb ssl-setup] has failures: true
Warning: /Stage[main]/Puppetdb::Server/Service[puppetdb]: Skipping because of failed dependencies
Info: /Stage[main]/Puppetdb::Server/Service[puppetdb]: Unscheduling all events on Service[puppetdb]
Info: Class[Puppetdb::Server]: Unscheduling all events on Class[Puppetdb::Server]
Warning: /Stage[main]/Puppetdb::Master::Config/Puppetdb_conn_validator[puppetdb_conn]: Skipping because of failed dependencies
Info: Class[Puppetdb::Master::Config]: Unscheduling all events on Class[Puppetdb::Master::Config]
Warning: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Skipping because of failed dependencies
Warning: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Skipping because of failed dependencies
Info: Class[Psick::Puppet::Foss_master]: Unscheduling all events on Class[Psick::Puppet::Foss_master]
Info: Class[Psick::Profiles]: Unscheduling all events on Class[Psick::Profiles]
Info: Class[Psick]: Unscheduling all events on Class[Psick]
Warning: /Stage[main]/Puppetdb::Master::Routes/File[/etc/puppetlabs/puppet/routes.yaml]: Skipping because of failed dependencies
Warning: /Stage[main]/Puppetdb::Master::Storeconfigs/Ini_setting[puppet.conf/master/storeconfigs]: Skipping because of failed dependencies
Warning: /Stage[main]/Puppetdb::Master::Storeconfigs/Ini_setting[puppet.conf/master/storeconfigs_backend]: Skipping because of failed dependencies
Warning: /Stage[main]/Puppetdb::Master::Report_processor/Ini_subsetting[puppet.conf/reports/puppetdb]: Skipping because of failed dependencies
Warning: /Stage[main]/Puppetdb::Master::Puppetdb_conf/Ini_setting[puppetdbserver_urls]: Skipping because of failed dependencies
Warning: /Stage[main]/Puppetdb::Master::Puppetdb_conf/Ini_setting[soft_write_failure]: Skipping because of failed dependencies
Info: Stage[main]: Unscheduling all events on Stage[main]
`
